# Generated by Django 5.0.7 on 2024-07-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=34)),
                ('marks', models.IntegerField()),
                ('gender', models.CharField(max_length=23)),
                ('city', models.CharField(max_length=23)),
            ],
        ),
    ]
